web:
  build: .
  volumes: 
   - build/tmp/docker:/tmp
  env_file: 
   - .env
  environment:
   - PORT=5000
   - PROFILE=production
  expose:
   - "5000"
   - "5001"
  ports:
   - "5000:5000"
   - "5001:5001"
