# APPLICATION SETTINGS (SpringApplication)
spring:
  profiles:
    active: ${profile:production}
  main:
    web-environment: true
  thymeleaf:
    cache: false

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: ${port:5000}
  session-timeout: 1800

logging:
  level:
    org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping: 'INFO'

info:
  app:
    name: ePages Demo App
    description: My awesome demo application
    version: DEV-SNAPSHOT


# http://localhost:5000/system/jmx/version
# http://localhost:5000/system/jmx/read/java.lang:type=Memory/HeapMemoryUsage
# curl -si -XPOST -H "Content-Type: application/json" -d '{"type":"read","mbean":"java.lang:type=Memory","attribute":"HeapMemoryUsage","path":"used"}' http://localhost:5000/system/jmx
management:
  context-path: /system

endpoints:
  configprops:
    keys-to-sanitize: password,secret,key,url
  env:
    keys-to-sanitize: password,secret,key,url
  health:
    enabled: true
    sensitive: false
    mapping:
      DOWN: SERVICE_UNAVAILABLE
  jmx:
    domain: DemoApp
    enabled: true
    unique-names: false
  jolokia:
    path: /jmx

jolokia:
  config:
    debug: true
